export interface Product {
  id: string;
  title: string;
  category: string;
  price: number;
  package: number;
  packageTitle: string;
  thumbnail: string;
  relatedProdIds: string[];
}

export const products: Product[] = [
  {
    id: 'p1',
    title: 'Organic Banana',
    category: 'Fruits&Vegetables',
    thumbnail: '',
    price: 0.27,
    package: 1,
    packageTitle: 'banana',
    relatedProdIds: ['p2', 'p3'],
  },
  {
    id: 'p2',
    title: 'Medium Hass Avocado',
    category: 'Fruits&Vegetables',
    thumbnail: '',
    price: 2.21,
    package: 1,
    packageTitle: 'avocado',
    relatedProdIds: ['p1', 'p3'],
  },
  {
    id: 'p3',
    title: 'Large tomatoes Hot House',
    category: 'Fruits&Vegetables',
    thumbnail: '',
    price: 1.04,
    package: 1,
    packageTitle: 'tomato',
    relatedProdIds: ['p1', 'p2'],
  },
  {
    id: 'p4',
    title: 'Coca-Cola zero sugar cola soda',
    category: 'Beverages',
    thumbnail: '',
    price: 9.89,
    package: 12,
    packageTitle: 'fl oz',
    relatedProdIds: ['p5', 'p6'],
  },
  {
    id: 'p5',
    title: 'Simply Pulp Free Orange Juice',
    category: 'Beverages',
    thumbnail: '',
    price: 5.49,
    package: 52,
    packageTitle: 'fl oz',
    relatedProdIds: ['p4', 'p6'],
  },
  {
    id: 'p6',
    title: 'Signature Select Refreshed Purified Drinki...',
    category: 'Beverages',
    thumbnail: '',
    price: 4.39,
    package: 24,
    packageTitle: 'fl oz',
    relatedProdIds: ['p4', 'p5'],
  },
  {
    id: 'p7',
    title: 'T.G.I. Friday’s Boneless Chicken Bites',
    category: 'Frozen',
    thumbnail: '',
    price: 10.44,
    package: 15,
    packageTitle: 'oz',
    relatedProdIds: ['p8', 'p9'],
  },
  {
    id: 'p8',
    title: 'Apple and Maple Froken Sausages',
    category: 'Frozen',
    thumbnail: '',
    price: 7.69,
    package: 55,
    packageTitle: 'fl oz',
    relatedProdIds: ['p7', 'p9'],
  },
  {
    id: 'p9',
    title: 'Top Ramen Frozen Chicken',
    category: 'Frozen',
    thumbnail: '',
    price: 8.49,
    package: 52,
    packageTitle: 'fl oz',
    relatedProdIds: ['p7', 'p8'],
  },
  {
    id: 'p10',
    title: 'yogi honey chai turmeric...',
    category: 'Pantry',
    thumbnail: '',
    price: 5.49,
    package: 16,
    packageTitle: 'tea bags',
    relatedProdIds: ['p11', 'p12'],
  },
  {
    id: 'p11',
    title: 'pillsbury sugarfree chocolate...',
    category: 'Pantry',
    thumbnail: '',
    price: 5.49,
    package: 12.4,
    packageTitle: 'oz',
    relatedProdIds: ['p10', 'p12'],
  },
  {
    id: 'p12',
    title: 'pillsbury family milk...',
    category: 'Pantry',
    thumbnail: '',
    price: 2.74,
    package: 18.4,
    packageTitle: 'oz',
    relatedProdIds: ['p10', 'p11'],
  },
  {
    id: 'p13',
    title: 'doritos nacho cheese',
    category: 'Groceries',
    thumbnail: '',
    price: 6.15,
    package: 9.3,
    packageTitle: 'oz',
    relatedProdIds: ['p14', 'p15'],
  },
  {
    id: 'p14',
    title: 'wheat thins sundried tomato &...',
    category: 'Groceries',
    thumbnail: '',
    price: 5.49,
    package: 8.5,
    packageTitle: 'oz',
    relatedProdIds: ['p13', 'p15'],
  },
  {
    id: 'p15',
    title: 'Doritos Cool Ranch Big Bag',
    category: 'Groceries',
    thumbnail: '',
    price: 6.15,
    package: 9.2,
    packageTitle: 'oz',
    relatedProdIds: ['p13', 'p14'],
  },
  {
    id: 'p16',
    title: 'Signature Farms Boneless Skinless Chicke...',
    category: 'Meat',
    thumbnail: '',
    price: 11.54,
    package: 1.5,
    packageTitle: 'lbs',
    relatedProdIds: ['p17', 'p18'],
  },
  {
    id: 'p17',
    title: 'Boar’s Head Turkey Honey Maple Glazed',
    category: 'Meat',
    thumbnail: '',
    price: 7.69,
    package: 12,
    packageTitle: 'oz',
    relatedProdIds: ['p16', 'p18'],
  },
  {
    id: 'p18',
    title: 'Jennie-O 93% Lean Ground...',
    category: 'Meat',
    thumbnail: '',
    price: 7.14,
    package: 16,
    packageTitle: 'oz',
    relatedProdIds: ['p16', 'p17'],
  },
  {
    id: 'p19',
    title: 'Open Nature Vegan non- Dairy',
    category: 'Cheese',
    thumbnail: '',
    price: 5.49,
    package: 8,
    packageTitle: 'oz',
    relatedProdIds: ['p20', 'p21'],
  },
  {
    id: 'p20',
    title: 'Primo Taglio Herb & Garlic Brie Cheese',
    category: 'Cheese',
    thumbnail: '',
    price: 7.7,
    package: 0.5,
    packageTitle: 'lb',
    relatedProdIds: ['p19', 'p21'],
  },
  {
    id: 'p21',
    title: 'Tillamook Sharp White Cheddar',
    category: 'Cheese',
    thumbnail: '',
    price: 5.49,
    package: 8,
    packageTitle: 'oz',
    relatedProdIds: ['p19', 'p20'],
  },
];
